name: Test Secrets

on:
  workflow_dispatch: # 手動実行できるようにする

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}"
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}"
